#!/usr/bin/env bash

# set proxies
export http_proxy=http://10.0.4.2:3128
export https_proxy=http://10.0.4.2:3128
export all_proxy=http://10.0.4.2:3128

# Run as user!

if [ "$EUID" -eq 0 ]
  then echo "Lancer ce script en tant qu'utilisateur"
  exit
fi

# clone the git repository
#cd ~
#git clone https://github.com/jfbercher/LecturesSignalProcessing.git
#cd ~/LecturesSignalProcessing

# Check if directories exist
if [ ! -d "~/.jupyter/nbconfig" ]; then
  mkdir -p ~/.jupyter/nbconfig
fi

# Change rights
sudo chown -R $USER:$USER ~/.local/share/jupyter 
sudo chown -R $USER:$USER ~/.jupyter/nbconfig 


# Install jupyter extensions
# latex_envs
pip3 install jupyter_latex_envs --user --upgrade
jupyter nbextension install --py latex_envs --user
jupyter nbextension enable latex_envs --user --py
# ipywidgets
pip3 install ipywidgets==6.0 --user # version 6 because the update causes problems
jupyter nbextension enable --py widgetsnbextension
# tiny extensions
jupyter nbextension install https://rawgit.com/jfbercher/small_nbextensions/master/highlighter.zip  --user
jupyter nbextension enable highlighter/highlighter 
jupyter nbextension install https://rawgit.com/jfbercher/small_nbextensions/master/interactive_sols.zip  --user
jupyter nbextension enable usability/interactive_sols/interactive_sols 
jupyter nbextension install https://rawgit.com/jfbercher/small_nbextensions/master/exercise.zip  --user
jupyter nbextension enable exercise/main 
jupyter nbextension install https://rawgit.com/jfbercher/small_nbextensions/master/exercise2.zip  --user
jupyter nbextension enable exercise2/main 
jupyter nbextension install https://rawgit.com/jfbercher/small_nbextensions/master/rubberband.zip  --user
jupyter nbextension enable rubberband/main 
jupyter nbextension install https://rawgit.com/jfbercher/small_nbextensions/master/toc2.zip  --user
jupyter nbextension enable toc2/main 
jupyter nbextension install https://rawgit.com/jfbercher/small_nbextensions/master/code_prettify.zip  --user
jupyter nbextension enable code_prettify/code_prettify

# Update rpy2
# pip3 install rpy2 --update --user 



##chmod executable files
#cd ~/LecturesSignalProcessing
#chmod 755 local_repo_update_ensg
 

