#!/usr/bin/env bash

# set proxies
export http_proxy=http://10.0.4.2:3128
export https_proxy=http://10.0.4.2:3128

# clone the git repository
cd ~
git clone https://github.com/jfbercher/LecturesSignalProcessing.git
cd ~/LecturesSignalProcessing

# Check if directories exist
if [ ! -d "~/.jupyter/nbconfig" ]; then
  mkdir -p ~/.jupyter/nbconfig
fi

# Install jupyter extensions
jupyter nbextension install https://rawgit.com/jfbercher/latex_envs/master/latex_envs.zip  --user
jupyter nbextension enable latex_envs/latex_envs  
jupyter nbextension install https://rawgit.com/jfbercher/small_nbextensions/master/highlighter.zip  --user
jupyter nbextension enable usability/highlighter/highlighter 
#jupyter nbextension install https://rawgit.com/jfbercher/small_nbextensions/master/interactive_sols.zip  --user
#jupyter nbextension enable usability/interactive_sols/interactive_sols 
jupyter nbextension install https://rawgit.com/jfbercher/small_nbextensions/master/exercise.zip  --user
jupyter nbextension enable usability/exercise/main 
jupyter nbextension install https://rawgit.com/jfbercher/small_nbextensions/master/exercise2.zip  --user
jupyter nbextension enable usability/exercise2/main 
jupyter nbextension install https://rawgit.com/jfbercher/small_nbextensions/master/rubberband.zip  --user
jupyter nbextension enable usability/rubberband/main 

#chmod executable files
cd ~/LecturesSignalProcessing
chmod 755 local_repo_update_ensg
 

